### ISSUE TITLE
Is there any way to parse a include able file at compile time?

### ISSUE THREAD

**Issue by Superlokkus** [boostorg/metaparse#10]
Because I am almost sure this is not documented or even missing, this question is the same as my SO question https://stackoverflow.com/q/59844966/3537677 :

Is there a way to separate the to be parsed DSL into a file? Like instead of

    using input = BOOST_METAPARSE_STRING("DSL content");
I want to use something like

    using input = BOOST_METAPARSE_STRING(#include "dsl.txt");
with dsl.txt containing

    DSL content
?

**Comment by sabel83** [comment]
I'm not aware of any better way of doing this, than what is already mentioned in the SO answers.
