### ISSUE TITLE
[Feature request] value based BOOST_METAPARSE_STRING macro analog

### ISSUE THREAD

**Issue by denzor200** [boostorg/metaparse#16]
Hi. I am using `boost::metaparse::string` for value-based metaprogramming.
For convenience, I created a macro for myself:
```
#ifdef BOOST_METAPARSE_MAKE_STRING
#error BOOST_METAPARSE_MAKE_STRING already defined
#endif
#define BOOST_METAPARSE_MAKE_STRING(S) (BOOST_METAPARSE_STRING(S){})
```
This macro allows me to write such statements succinctly and without unnecessary parentheses:
``` 
field<int, (name=BOOST_METAPARSE_MAKE_STRING("id"))> index;
field<std::string, (name=BOOST_METAPARSE_MAKE_STRING("user"))> username;
```
In modern C++(example above is C++17), the value-based metaprogramming approach is very often used. I believe that this macro will be useful not only for me. Why not add it to the library?

**Comment by sabel83** [comment]
Hi. I've added the macro on the `string_value` branch in my fork of this repository (see https://github.com/sabel83/metaparse/tree/string_value). Note that I've renamed it to `BOOST_METAPARSE_STRING_VALUE` as its purpose is to provide a value.

Please take a look and let me know if this works for you.

**Comment by denzor200** [comment]
@sabel83 Cool! This is what i need. Thanks

**Comment by sabel83** [comment]
It is now merged to the `master` branch and will be part of the next release. Thank you for your suggestion.
